### ISSUE TITLE
SignUp / UI 작성

### ISSUE THREAD

**Issue by shippingpark** [AdultOfNineteen/WINEY-iOS#26]
# 🍷요약
* SignUp 로직 UI 완성 
* animation 이슈 해결 
* UIApplication 확장으로 키보드 내림 메서드 생성 : WineyKit 모듈에 정의 
* Winkit 내 WineyStyleGuide 폴더 생성 / WineyGridRules 내부에 padding 규칙 정의 
* 🔥현재 빠른 Test 위해 버튼 비활성화 처리 X : API 엮으며 다잡을 예정 
# ✅ 체크 포인트
- [x] CodeSignupView에서 사용 될 bottomSheet 종류 분류 
✔️ 바텀 시트 화면 종류를 만들어 재사용하는 게 아닌 사용 시에 header, content, footer를 작성하여 삽입하도록 생성하였는데, 
Phone -> Code -> Flavor에 걸쳐 일부 재사용 되므로  전체적으로 만들어 두는 게 좋을 지 고민 중입니다. (현재는 뷰마다 조립형태)
```swift
.bottomSheet(
          backgroundColor: WineyKitAsset.gray950.swiftUIColor,
          isPresented: viewStore.binding(
            get: \.isPresentedBottomSheet,
            send: .tappedOutsideOfBottomSheet
          ),
          headerArea: {
            CodeSignUpBottomSheetHeader()
          },
          content: {
            CodeSignUpBottomSheetContent(
              store: store.scope(
                state: \.bottomSheetType,
                action: { CodeSignUpAction.tappedOutsideOfBottomSheet } // 양식 맞춤
              )
            )
          },
          bottomArea: {
            HStack {
              CodeSignUpBottomSheetFooter(
                store: store // 분리해서 넣는 게 좋을까 논의
              )
            }
            .padding(.horizontal, WineyGridRules.globalHorizontalPadding)
          }
        )
```
분류를 하여도 바텀 시트 뷰 전체를 분류하는 것이 아닌 header, contents, footer 기준으로 생성, 분류하였습니다. 
최대한 유연한 형태를 구성하고자 했습니다. 
그러나 아래 View는 재사용 되는 코드 중에서도 그 길이가 짧지 않아 별도의 Component로 분리하였습니다 
<img width="232" alt="image" src="https://github.com/AdultOfNineteen/WINEY-iOS/assets/81788774/1c5ff3bd-a339-4d0e-94c3-0279de51a77c">
```swift
public struct TwoOptionSelectorButtonView: View {
  let leftTitle: String
  let leftAction: () -> Void
  let rightTitle: String
  let rightAction: () -> Void
  
  public init(
    leftTitle: String,
    leftAction: @escaping () -> Void,
    rightTitle: String,
    rightAction: @escaping () -> Void
  ) {
    self.leftTitle = leftTitle
    self.leftAction = leftAction
    self.rightTitle = rightTitle
    self.rightAction = rightAction
  }
  
  public var body: some View {
    VStack(spacing: 5) {
      Rectangle()
      .frame(height: 1)
      .foregroundColor(WineyKitAsset.gray700.swiftUIColor)
      ZStack {
        Rectangle()
          .frame(width: 1, height: 25)
          .foregroundColor(WineyKitAsset.gray700.swiftUIColor)
        HStack(spacing: 0) {
          HStack(spacing: 0) {
            Spacer()
            Button(leftTitle) {
              leftAction()
            }
            .foregroundColor(WineyKitAsset.gray100.swiftUIColor)
            .wineyFont(.headLine)
            Spacer()
          }
          HStack(spacing: 0) {
            Spacer()
            Button(rightTitle) {
              rightAction()
            }
            .foregroundColor(WineyKitAsset.gray600.swiftUIColor)
            .wineyFont(.headLine)
            
            Spacer()
          }
        }
      }
      .frame(height: 55)
    }
  }
}
```

- [x] UI 관련 Extension은 WineyKit에 분류하였습니다 
- [x] API 경로를 고려하며 설계하였으나 통신 코드 작성하며 수정이 이루어질 수 있습니다 

# 💻Task
* bottomSheet 호출에 animation, transition으로 인한 padding 버벅임 이슈: 해결 
=> ZStack 상에서 animation 선언 위치 문제였습니다 

# 🔥 의논사항 
1️⃣ 폴더 분류가 고민입니다. 지금처럼 View와 Core를 한 군데 몰아 넣는게 아닌 따로 분류해도 괜찮지 않을까 생각합니다 
2️⃣ 하드코딩되는 padding 값과 String 값 처리가 고민입니다. View.swift 최상단에 enum 또는 struct로 정의해도 괜찮지 않을까? 생각하고 있습니다
